### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by rictorres** [mattpker/pm2-slack#1]
First of all, thanks for this module :)

I'm experiencing some weird memory usage on my system.

![image](https://cloud.githubusercontent.com/assets/351568/10849515/5d33ddb4-7f21-11e5-810e-fcbf7334e58f.png)

120MB for such a tiny module seems a bit odd, what are your thoughts on this? I didn't have time to debug this yet but maybe you or someone else already have some insights.

**Comment by mattpker** [comment]
I checked all my servers I have it running on and they are all in the 30's for MB (the process has been running for well over a week on all of them). I have noticed in the past that the more memory my system has, the more memory Node likes to consume. I think it may be a caching thing. 

How much memory do you have on this system? Mine are between 4 - 8 GB. You may also want to do a heap dump on it and see if you can find what is using all the memory. Also try doing an 'lsof -p {pid}', and see if anything sticks out as using a lot of memory.

Thanks for the feedback!

**Comment by rictorres** [comment]
This is the output of `lsof -p {pid}`.

```
COMMAND   PID   USER   FD   TYPE             DEVICE SIZE/OFF    NODE NAME
node    21918 ubuntu  cwd    DIR              202,1     4096  335951 /home/ubuntu/.pm2/node_modules/pm2-slack
node    21918 ubuntu  rtd    DIR              202,1     4096       2 /
node    21918 ubuntu  txt    REG              202,1 17284159  288335 /home/ubuntu/.nvm/versions/io.js/v2.5.0/bin/iojs
node    21918 ubuntu  mem    REG              202,1   101240  396095 /lib/x86_64-linux-gnu/libresolv-2.19.so
node    21918 ubuntu  mem    REG              202,1    22952  396073 /lib/x86_64-linux-gnu/libnss_dns-2.19.so
node    21918 ubuntu  mem    REG              202,1    47712  396074 /lib/x86_64-linux-gnu/libnss_files-2.19.so
node    21918 ubuntu  mem    REG              202,1  1840928  396040 /lib/x86_64-linux-gnu/libc-2.19.so
node    21918 ubuntu  mem    REG              202,1   141574  396093 /lib/x86_64-linux-gnu/libpthread-2.19.so
node    21918 ubuntu  mem    REG              202,1    90080  396054 /lib/x86_64-linux-gnu/libgcc_s.so.1
node    21918 ubuntu  mem    REG              202,1  1071552  396063 /lib/x86_64-linux-gnu/libm-2.19.so
node    21918 ubuntu  mem    REG              202,1   979056     284 /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
node    21918 ubuntu  mem    REG              202,1    14664  396049 /lib/x86_64-linux-gnu/libdl-2.19.so
node    21918 ubuntu  mem    REG              202,1    31792  396096 /lib/x86_64-linux-gnu/librt-2.19.so
node    21918 ubuntu  mem    REG              202,1   149120  396030 /lib/x86_64-linux-gnu/ld-2.19.so
node    21918 ubuntu    0u  unix 0x0000000000000000      0t0 1045176 socket
node    21918 ubuntu    1u  unix 0x0000000000000000      0t0 1045178 socket
node    21918 ubuntu    2u  unix 0x0000000000000000      0t0 1045180 socket
node    21918 ubuntu    3u  unix 0x0000000000000000      0t0 1045182 socket
node    21918 ubuntu    4r  FIFO                0,8      0t0 1045184 pipe
node    21918 ubuntu    5w  FIFO                0,8      0t0 1045184 pipe
node    21918 ubuntu    6u  0000                0,9        0    5385 anon_inode
node    21918 ubuntu    7r  FIFO                0,8      0t0 1045185 pipe
node    21918 ubuntu    8w  FIFO                0,8      0t0 1045185 pipe
node    21918 ubuntu    9u  0000                0,9        0    5385 anon_inode
node    21918 ubuntu   10r   CHR                1,3      0t0    5430 /dev/null
node    21918 ubuntu   12u  unix 0x0000000000000000      0t0 1045189 socket
```

`pm2-slack` is running on a micro EC2 instance with 1GB RAM.

![image](https://cloud.githubusercontent.com/assets/351568/11115685/a56d9578-892d-11e5-9c74-2739d19a6fa8.png)

I'm gonna try to do a heap dump and inspect the results.

Thanks!

**Comment by mattpker** [comment]
How big is the messages that you are sending to Slack. It could be that it is keeping the last message in memory and the last request in memory (using the request module). I am still only experiencing 30 to 40MB of memory usage on all of my instances and they have been sending a lot of messages into slack. I see that it looks like you are using io.js. You might want to try to update to the Node 4.1.\* versions, that is what I am running.

**Comment by rictorres** [comment]
Not big, just "app start/stop/restart".

I'm gonna try updating Node.js to v4.x and check the results.

**Comment by mattpker** [comment]
Just read this article today, if upgrading to v4.x fixes your problems this might be why.

http://goldfirestudios.com/blog/140/Massive-Memory-Gains-in-Node.js-4.2?utm_source=nodeweekly&utm_medium=email

**Comment by mattpker** [comment]
I have not heard any other reports on this issue or heard back from @rictorres. For now I am recommending that people be at least running the LTS version of Node. Please let me know if you experience memory issues on Node v4.x or greater.
