### ISSUE TITLE
App specific log events and regex specific log string match

### ISSUE THREAD

**Issue by knvpk** [mattpker/pm2-slack#11]
I have a node application for downloading some files daily in that application it shows the progress in the command but i want only specific log messages to be notified when the specified regex is matched to the log name or description. Also i want to notify only for specific app process because pm2 can be processed for many apps

**Comment by mattpker** [comment]
This is out of the scope of this project. I recommend that you fork the project and added the regex support that you need.

For per app logging, I recommend that you run each of your apps as a different linux user. Each linux user has their own pm2 process and pm2-slack module.

**Comment by knvpk** [comment]
I think its not a good solution for creating user per process, Ok Anyway i will make my own pm2 module. Thnaks for this.
