### ISSUE TITLE
pm2 reload

### ISSUE THREAD

**Issue by AdriVanHoudt** [mattpker/pm2-slack#12]
Is there a way to notify on a reload? Either from `pm2 reload` or due to the `--max-memory-restart` flag?

**Comment by mattpker** [comment]
I am listening for all the events that pm2 provides to modules. Please review the options in the README for the events that you can subscribe to.

**Comment by AdriVanHoudt** [comment]
Well I have it set to the defaults with `restart: true` and `error: false` and I thought it would log reload due to `restart` but it does not. The options in the readme do not state `reload`. And I can't find docs for the events, do you have any clues?

**Comment by mattpker** [comment]
Did some testing and there is a reload event that is fired that is undocumented by PM2. I have added the documentation to pm2-slack. Just set:

```pm2 set pm2-slack:reload true```

to turn it on.

**Comment by AdriVanHoudt** [comment]
@mattpker thanks a ton! 🎉
