### ISSUE TITLE
Add id to title

### ISSUE THREAD

**Issue by AdriVanHoudt** [mattpker/pm2-slack#15]
Would it be possible to add the id of the process to the message title?
If you have 4 processes with the same name this helps to see where an event happened.

**Comment by mattpker** [comment]
@ma-zal seems like something easy to add... would you like to tackle this one?

**Comment by abawchen** [comment]
@ma-zal & @mattpker 
Which process id do you want to add? pm_id(pm2 id) or pid(os process id)? I guess pm_id is enough, right?

I think I can help this easy one -- does it need to be configrable(show or hide)? or just display as name[id] by default.

@mattpker : this tool does save my day :)

**Comment by mattpker** [comment]
@abawchen I assume they would just need the pm2 process id. That way when they do a `pm2 status` they can see which pm2 process specifically is having issues.

I would vote for it just to be defaulted on with no config to turn it off. I don't see a reason why someone would specifically not want to display that in the slack messages.

**Comment by mattpker** [comment]
Fixed by #23
