### ISSUE TITLE
Increase buffer seconds limit

### ISSUE THREAD

**Issue by mateeyow** [mattpker/pm2-slack#16]
Is there a reason why the maximum buffer second limit is only 5 seconds? I have a usecase that I need it to send only every 10/30 seconds.

**Comment by ma-zal** [comment]
I improved the buffer algorithm. My version has no limitation. I opened the pull request https://github.com/mattpker/pm2-slack/pull/21 for it.

**Comment by mattpker** [comment]
#21 will fix this issue, closing
