### ISSUE TITLE
Error when I try to install

### ISSUE THREAD

**Issue by Ridermansb** [mattpker/pm2-slack#17]
Refusing to download the git repo 

```
{"protocol":"http:","hostname":"ikt.pm2.io","repository":"http://ikt.pm2.io/ikt.git"} over HTTP without a commit hash
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Environment:**
DigitalOcean, Alpine Linux (inside the docker container)

**Comment by mattpker** [comment]
Have you tried using NPM rather then yarn? You can also just directly git clone the master branch and then cd to the directory and run 'pm2 install .'

**Comment by Ridermansb** [comment]
The install is done via docker using [pm2-docker-alpine][1] image

```
FROM keymetrics/pm2-docker-alpine
RUN pm2 install pm2-slack
```

[1]: https://hub.docker.com/r/keymetrics/pm2-docker-alpine/
