### ISSUE TITLE
Multiple slack_url

### ISSUE THREAD

**Issue by dody87** [mattpker/pm2-slack#20]
Hi, is there a way to configure 2 or more slack webhook urls? I have two channels and I need to set two webhooks or at least set different channels from PM2 module.

Maybe it's done but i didn't find it.

Thanks in advance.

**Comment by mattpker** [comment]
Currently only one webhook is supported.

Just like #4, I recommend for now to setup your app's per user on linux for different configs.

Ill leave this open for a future possible feature if I get time to work on it.

Feel free to submit a pull request if you have an idea on how to do it.

Thanks!

**Comment by ma-zal** [comment]
See the pull request https://github.com/mattpker/pm2-slack/pull/22 and test it please.

**Comment by mattpker** [comment]
Fixed by #22
