### ISSUE TITLE
Keep pm2-slack backwards compatible with old versions of node

### ISSUE THREAD

**Issue by mattpker** [mattpker/pm2-slack#24]
@ma-zal Can we please change the `const` to a `var`? Realized this breaks some of my really old applications when running node without the `--harmony` flag.

https://github.com/mattpker/pm2-slack/blob/8a0ed779feced06a6ad61d2a9d460c5b3e6cb142/index.js#L114

**Comment by ma-zal** [comment]
Native support of `const` exists since NodeJS 4, that has been released in 2015.
Do we really want to support really old NodeJS 0.10? :-( I cannot imagine, then somebody is running on NodeJS 0.10 on production today without any security updates.

**Comment by mattpker** [comment]
For now I would, you would be surprised how long it take to get stuff updated. lol

**Comment by ma-zal** [comment]
Closing as outdated.
