### ISSUE TITLE
Is it a bug in cluster mode?

### ISSUE THREAD

**Issue by abawchen** [mattpker/pm2-slack#26]
I have an app running in cluster mode that every time I restart it, there would be two `null` messages as follows:

<img width="651" alt="screen shot 2017-11-17 at 3 05 55 pm" src="https://user-images.githubusercontent.com/2952415/32935003-b33bfda8-cb33-11e7-9ca8-d8b1f9a6f6b9.png">

**Comment by mattpker** [comment]
@abawchen Feel free to research this one, I don't think it should be happening.

**Comment by abawchen** [comment]
Well, when I update the version to 1.1.0, it works well :p

<img width="610" alt="screen shot 2017-11-20 at 12 45 50 pm" src="https://user-images.githubusercontent.com/2952415/33002717-dfc402b6-cdf0-11e7-866a-74eeb72ce7c9.png">
