### ISSUE TITLE
error on install `Unknown module`

### ISSUE THREAD

**Issue by Sigura** [mattpker/pm2-slack#5]
Hello

first, thank you for your wonderful work!

I got this error on my gliderlabs/alpine:3.3 image

log:

``` bash
$ pm2 install pm2-slack
[PM2][Module] Installing module pm2-slack
[PM2][Module] Module already installed. Updating.
[PM2][Module] Processing...
............/root/.pm2
`-- pm2-slack@0.3.0

[PM2][Module][ERROR] Unknown module
```

**Comment by mattpker** [comment]
What version of pm2 are you using? Have you tried uninstalling the pm2-slack module first and reinstalling? Have you tried updating pm2?

**Comment by Sigura** [comment]
Matthew, sorry for late answer.

``` bash
# pm2 -v
1.1.3
# npm -v
3.8.7
# node -v
v4.3.0
```

I will try to find something to get debug output on install

**Comment by Sigura** [comment]
issue gone when I downgrade pm2 to version 1.1.2

**Comment by mattpker** [comment]
Strange, not much changed between those versions. 

https://github.com/Unitech/pm2/blob/master/CHANGELOG.md

I'll take at look into it on Monday. Thanks for all the information.

**Comment by mattpker** [comment]
I installed PM2 version 1.1.3 and was able to fresh install pm2-slack without any issue. I also did a second install to force an update and that also worked without issue.

I would need some sort of detailed log output to be able to troubleshoot this further.

**Comment by Sigura** [comment]
Now I think it's not a pm2 and pm2-slack problem. I'm sure something broken in npm or node package after success installation.

Sorry for bother.

**Comment by Sigura** [comment]
yes, re-install npm and node helps.

**Comment by mattpker** [comment]
Awesome. Thanks for letting me know. I will consider this issue closed.
