### ISSUE TITLE
How can I strip terminal color code

### ISSUE THREAD

**Issue by soichih** [mattpker/pm2-slack#7]
Hello. 

My application is outputting logs using winston with colorize option set to true. This allows me to see logs that is colorized based on the log type (error shows up in red, etc..) 

Now, since pm2-slack sends logs to slack without stripping the terminal color code, I am seeing something like following in the slack channel.

```
my.host.com BOT [3:44 AM]  
sca-wf-task - error
----------------
"Thu Oct 06 2016 07:44:01 GMT+0000 (UTC) - \u001b[31merror\u001b[39m: can't clean taskdir on resource_id:575ef81e9b8f34d642b15106 because resource status is not ok\n"
```

Is there anyway to strip those terminal color codes like.. `\u001b[31m`?

**Comment by vineyugave** [comment]
Did anyone figure this out ?

**Comment by mattpker** [comment]
Looks like that is unicode, I would be worried that if I tried to strip out unicode that it might actually strip out something important that someone might need. I will look into terminal colors and see if I can come up with a regex or something to only strip those.

As this is only a presentation issue and not a breaking bug this will be set to a low priority bug. I probably wont be able to get to it for a few weeks (my Wife just had a baby), so if anyone has any ideas to fix this or can help out, that would be appreciated.

Thanks for reporting this issue.

**Comment by dpiasecki** [comment]
I'm not sure if this is the best solution, but it is what worked for me. I tried a few different things and found that the `JSON.stringify` were causing multiple issues, including the log messages in Slack actually showing the \n instead of converting it to a new line. So I added the `strip-ansi` package and replaced the `JSON.stringify` with `stripAnsi`
1. Add the `strip-ansi` package:
   `npm install strip-ansi --save`
2. Modify index.js:

```
6a7
> var stripAnsi = require('strip-ansi');
150c151
<                     description: JSON.stringify(data.data),
---
>                     description: stripAnsi(data.data),
164c165
<                     description: JSON.stringify(data.data),
---
>                     description: stripAnsi(data.data),
190c191
<                     description: JSON.stringify(data.data),
---
>                     description: stripAnsi(data.data),
```

**Comment by mattpker** [comment]
@soichih can you please test if this is fixed in version 0.3.1

**Comment by soichih** [comment]
@mattpker 

I've updated to v0.3.1. The output looks better, but I don't think it's fixed ??

```
sca-progress - error
----------------
Fri Feb 17 2017 00:21:45 GMT+0000 (UTC) - [34mdebug[39m: key:_sca.58a5ab1d3e74b77dbc65a017.58a5ab323e74b77dbc65a01c
{
   "status": "running",
   "progress": 79.65,
   "msg": "Executing recon_all"
}

Fri Feb 17 2017 00:21:46 GMT+0000 (UTC) - [34mdebug[39m: updating _sca.58a5ab1d3e74b77dbc65a017.58a5ab323e74b77dbc65a01c
```

**Comment by mattpker** [comment]
After some research I do not feel comfortable stripping any sort of code from log/error messages. The point of this module is to dump all of an error/log message to slack and trying to strip code from these messages might end up removing something someone may actually need in their slack messages. As this is just a cosmetic request and is out of the scope of this module, I am considering this issue closed.
