### ISSUE TITLE
slack message not formal.

### ISSUE THREAD

**Issue by sabper** [mattpker/pm2-slack#9]
hello. i'm using pm2-slack module.

slack message not formal.

ex.

"2017-02-16T10:00:00.729Z - \u001b[31merror\u001b[39m: [ auth/email-already-in-use ] The email address is already in use by another account. \n{ email: \u001b[32m'jwyoon@barogo5.com'\u001b[39m,\n  password: \u001b[32m'barogo1004!'\u001b[39m,\n  phone: \u001b[32m'0111111242'\u001b[39m }\n"

why print this message?

this module verfy useful to me..

thank you!

**Comment by mattpker** [comment]
This is fixed in the latest version I just release: 0.3.1 Fixed Double escaping of error and log messages
